### ISSUE TITLE
SVG image

### ISSUE THREAD

**Issue by thoo** [choldgraf/sphinx-copybutton#12]
Thanks for this great extension. If I want to use a different image instead of `sphinx_copybutton/_static/copy-button.svg`, can I overwrite it in css file some way???

**Comment by choldgraf** [comment]
oooh good question...hmm, currently no (the path to the SVG is hard-coded). But either:

1. We could try adding a configuration to `conf.py` that would let the user set this path.
2. We could check for a file called `_static/copybutton.svg` and if it exists use that file instead of the default one.
3. We could provide documentation for how to change this button with Javascript after the site is loaded.

Any thoughts? :-)

**Comment by thoo** [comment]
@choldgraf  Thanks for the quick reply. It would we nice to have an option to configure in `conf.py`. I submitted PR for `scikit-image` to add a copybutton using your extension. Hopefully, more python machine learning communities use your extensions. Tensorflow already had a copy button. 👍

**Comment by choldgraf** [comment]
ok cool, lemme see if I can figure this one out...shouldn't be too hard (or PRs are welcome as well!)

**Comment by choldgraf** [comment]
hmmm, I looked into it a little bit, and I can't figure out how to set a javascript variable using a configuration in `conf.py`...sphinx extensions is such a mystery to me :-P

could you try a hacky solution to this first? :-)

If you did these two things:

1. included your own javascript with the site (e.g., in `_static/js/custom.js`) like the following example (which loads a random other image instead of the default copy button image):

```javascript
const updateCopyButtonImages = () => {
	const copybuttonimages = document.querySelectorAll('a.copybtn img')
	copybuttonimages.forEach((img, index) => {
	   img.setAttribute('src', 'http://www.clker.com/cliparts/2/2/8/6/11949945221692172998copy.svg.hi.png')
	})
}

runWhenDOMLoaded(updateCopyButtonImages)
```

2. Add that stylesheet to your `conf.py` configuration like so:

```python
def setup(app):
   app.add_javascript('js/custom.js');
```

then it should update the images on site load. Does that work for you?

**Comment by thoo** [comment]
Thanks. I think it should work. I will close the issue for now. If I run into issues, I will get back to you. :) Thanks for the help.

**Comment by choldgraf** [comment]
cool - I added these instructions here: #14
