### ISSUE TITLE
Support copying content without the prompt

### ISSUE THREAD

**Issue by adamtheturtle** [choldgraf/sphinx-copybutton#30]
This is a feature request.

I use [`sphinx-prompt`](https://pypi.org/project/sphinx-prompt/) which allows a user to select the script but not the prompt.

It would be great to use this with `sphinx-copybutton`.

**Comment by choldgraf** [comment]
Ah yes - I agree that some version of supporting this would be helpful! We had take a stab at it in https://github.com/choldgraf/sphinx-copybutton/pull/20 but eventually closed it because it seemed to vulnerable to edge-case-splosion. Maybe an easier way to fix this would be to allow the user to supply a function that is called on the text of the code cell before the copy is returned? If you've got a relatively straightforward idea for how to implement a solution to this problem, I'm happy to review a PR!

**Comment by adamtheturtle** [comment]
I do not have any ideas, sorry!

**Comment by choldgraf** [comment]
see #49 for an implementation that addresses this. It lets users specify some custom text, which will be removed from the beginning of any lines that start w/ that text

**Comment by jorisvandenbossche** [comment]
Would there also be interest in doing this for _manual_ copying, instead of only for the copy button? (i.e. so closer to what https://github.com/sbrunner/sphinx-prompt is doing) 
Or is that considered out of scope for this project?

**Comment by choldgraf** [comment]
@jorisvandenbossche can you describe in more detail what you mean? I'm not sure I follow (feel free to open a new issue if that makes it easier to scope)
